### ISSUE TITLE
vim82での設定?

### ISSUE THREAD

**Issue by kozo2** [deton/tcvime#8]
Windowsのgvim.exeをvim-jpが配布しているvim81-kaoriya-win64からvim82に切り替えたところ
```
tcvime#InputPostConvert(
```
が効かなくなっているように思いました。
tcodeのキーマップは使えています。
問題の調査方法等何かアイデアがあればお教えください。
私の _vimrc は
```
nnoremap ; :
nnoremap : ;
inoremap jj <Esc>
inoremap kk <Esc>

set autochdir

if has('keymap')
  let tcvime_keymap = 'tcode'
  set iminsert=0 imsearch=0
  imap <unique> <C-J> <Plug>TcvimeIEnableKeymap
  imap <silent> <unique> <C-L> <Plug>TcvimeIDisableKeymap
  imap <silent> <unique> <ESC> <ESC>:set imsearch=0<CR>
  imap <silent> <unique> <C-K>/ <Plug>TcvimeIAsciiStart
endif

function TcvimeCustomKeymap()
  " tc2同様の後置型交ぜ書き変換を行うための設定:
  " " 活用しない語
  lmap <silent> 18 <C-G>u<C-R>=tcvime#InputPostConvert(1, 0)<CR>
  lmap <silent> 28 <C-G>u<C-R>=tcvime#InputPostConvert(2, 0)<CR>
  lmap <silent> 38 <C-G>u<C-R>=tcvime#InputPostConvert(3, 0)<CR>
  lmap <silent> 48 <C-G>u<C-R>=tcvime#InputPostConvert(4, 0)<CR>
  lmap <silent> 58 <C-G>u<C-R>=tcvime#InputPostConvert(5, 0)<CR>
endfunction
```
です。

**Comment by kozo2** [comment]
```
tcvime#InputPostConvert(
```
の初回失敗時に下記画像のように交ぜ書き変換辞書ファイルのオープンに失敗するようです。

![image](https://user-images.githubusercontent.com/12192/71430470-5eff3e00-270f-11ea-9605-46d3ed0da6f8.png)

**Comment by deton** [comment]
mazegaki.dicが&runtimepath内に複数あると読込失敗するバグがあったので、
#9 で修正しました。

**Comment by kozo2** [comment]
#9 ありがとうございます。
ただ #9 でも「交ぜ書き変換辞書ファイルのオープンに失敗しました」のメッセージは出なくなったものの `tcvime#InputPostConvert` は有効化されず変換が行えないに思いました

**Comment by deton** [comment]
上掲の_vimrcで試したところ、手元で現象を再現できました。
utf-8のmazegaki.dicがcp932として読み込まれて文字化けしています。

_vimrcに、utf-8を読み込めるようにする、以下のような設定を入れれば動作するはずです。
```viml
set fileencodings=ucs-bom,utf-8,default
```
(&fileencodingsのデフォルトは、ucs-bomのみの模様。&encodingはcp932)

または、READMEにあるように、
>  辞書ファイルや.txtファイルの漢字コードはUTF-8です。
>  EUC-JPやCP932環境で、各ファイルをvimでそのまま開いても正しく読めない場合は、
>  環境に合わせて漢字コードを変換しておいてください。
>  (でないと各ファイルを使う部首合成変換や交ぜ書き変換が動作しません)

**Comment by kozo2** [comment]
ありがとうございます。仰る設定により `tcvime#InputPostConvert` を利用することが可能になりました。
